// プレイリスト定義: assets/sound 内の楽曲一覧
const TRACKS = [
  { title: "Track A", file: "assets/sound/A.mp3" },
  { title: "Track B", file: "assets/sound/B.mp3" },
  { title: "Track C", file: "assets/sound/C.mp3" },
  { title: "Track D", file: "assets/sound/D.mp3" },
  { title: "Track E", file: "assets/sound/E.mp3" },
  { title: "Track F", file: "assets/sound/F.mp3" },
  { title: "Track G", file: "assets/sound/G.mp3" },
  { title: "Track H", file: "assets/sound/H.mp3" },
  { title: "Track I", file: "assets/sound/I.mp3" },
  { title: "Track J", file: "assets/sound/J.mp3" },
  { title: "Track K", file: "assets/sound/K.mp3" },
  { title: "Track L", file: "assets/sound/L.mp3" },
  { title: "Track M", file: "assets/sound/M.mp3" },
  { title: "Track N", file: "assets/sound/N.mp3" },
  { title: "Track O", file: "assets/sound/O.mp3" },
  { title: "Track P", file: "assets/sound/P.mp3" },
  { title: "Track Q", file: "assets/sound/Q.mp3" },
  { title: "Track R", file: "assets/sound/R.mp3" },
  { title: "Track S", file: "assets/sound/S.mp3" },
  { title: "Track T", file: "assets/sound/T.mp3" },
  { title: "Track U", file: "assets/sound/U.mp3" },
  { title: "Track V", file: "assets/sound/V.mp3" },
  { title: "Track W", file: "assets/sound/W.mp3" },
  { title: "Track X", file: "assets/sound/X.mp3" },
  { title: "Track Y", file: "assets/sound/Y.mp3" },
  { title: "Track Z", file: "assets/sound/Z.mp3" },
];
